{
    "cs" : {
        "Settings_table" : "Nastavení",
        "Name" : "Název",
        "Time_from" : "Od",
        "Time_to" : "Do",
        "Type" : "Typ",
        "Action" : "Akce",
        "Create_settings":"Přidat nastavení",
        "Mode":"Režim",
        "Pulse":"Pulsní",
        "Interval":"Interval",
        "Sequential":"Sekvence",
        "Pulse_type":"Typ pulsů",
        "Random":"Náhodné",
        "Interval_time":"Časování intervalu",
        "Minutes":"Minuty",
        "Hour":"Hodiny",
        "Sequential_time":"Start sekvence",
        "Seconds":"Sekundy",
        "OUT12":"Výstup 1 & 2",
        "OUT34":"Výstup 3 & 4",
        "P1Max":"P1 Max %",
        "P2Max":"P2 Max %",
        "P3Max":"P3 Max %",
        "P4Max":"P4 Max %",
        "P1Min":"P1 Min %",
        "P2Min":"P2 Min %",
        "P3Min":"P3 Min %",
        "P4Min":"P4 Min %",
        "Pulse_flow":"Délka pulsu",
        "From_time":"Od (hh:mi)",
        "To_time":"do (hh:mi)",
        "Add":"Přidat",
        "Global":"Celkové nastavení",
        "Food_delay":"Krmící pauza (v min.)",
        "Food_times":"Časy krmení",
        "Storm_timer":"Časovač bouře (každých X hodin)",
        "Save":"Uložit",
        "Ramp":"Rozběh"
        }
    }