{
    "en" : {
        "Settings_table" : "Settings table",
        "Name" : "Name",
        "Time_from" : "From",
        "Time_to" : "To",
        "Type" : "Type",
        "Action" : "Action",
        "Create_settings":"Create named settings",
        "Mode":"Mode",
        "Pulse":"Pulse",
        "Interval":"Interval",
        "Sequential":"Sequential",
        "Pulse_type":"Pulse_type",
        "Random":"Random",
        "Interval_time":"Interval Time",
        "Minutes":"Minutes",
        "Hour":"Hour",
        "Sequential_time":"Sequential",
        "Seconds":"Seconds",
        "OUT12":"Out 1 & 2",
        "OUT34":"Out 3 & 4",
        "P1Max":"P1 Max",
        "P2Max":"P2 Max",
        "P3Max":"P3 Max",
        "P4Max":"P4 Max",
        "P1Min":"P1 Min",
        "P2Min":"P2 Min",
        "P3Min":"P3 Min",
        "P4Min":"P4 Min",
        "Pulse_flow":"Pulse flow",
        "From_time":"From Time",
        "To_time":"To Time",
        "Add":"Add",
        "Global":"Global",
        "Food_delay":"Food delay (in minutes)",
        "Food_times":"Food times (HH:MI) separated by ;",
        "Storm_timer":"Storm timer (every X hours)",
        "Save":"Save",
        "Ramp":"Ramp Time"
    }
}
